import type { ShowInfo, ShowMember, ShowTask, TaskDeliverable, User } from '../types';
const base = (import.meta as ImportMeta & {env:Record<string,string>}).env.VITE_API_URL || 'http://localhost:4000/api';
let userId = localStorage.getItem('sgt_dev_user_id') || '';
export const setApiUser = (id:string) => { userId=id; localStorage.setItem('sgt_dev_user_id',id); };
async function request<T>(path:string, init:RequestInit={}):Promise<T>{const response=await fetch(`${base}${path}`,{...init,headers:{'Content-Type':'application/json',...(userId?{'x-user-id':userId}:{}),...init.headers}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||`API error ${response.status}`);}return response.status===204?undefined as T:response.json();}
const mapShow=(s:any):ShowInfo=>({...s,date:new Date(s.showDate).toLocaleDateString('vi-VN'),locationCity:s.city,time:s.startTime,apiStatus:s.status,status:s.status==='COMPLETED'?'COMPLETED':s.status==='CANCELLED'?'CANCELLED':s.status==='READY'?'IN_PROGRESS':'UPCOMING',scale:s.scale||'',goal:s.goal||'',personnel:{pm:s.members?.find((m:any)=>m.role==='PM')?.user.name||'Chưa phân công',se:s.members?.find((m:any)=>m.role==='SE')?.user.name||'Chưa phân công',ctvCount:0,htvCount:0},lineup:{host:'',comedians:[]},pricing:[],shifts:[],social:{},ticketTotalTarget:0,ticketSold:0});
const priorityFromApi=(p:string)=>p==='URGENT'?'Khẩn cấp':p==='IMPORTANT'?'Quan trọng':'Bình thường';
const mapTask=(t:any):ShowTask=>({...t,showName:t.show?.name,category:t.category||'TASK NGOÀI (AD-HOC)',pic:t.assignees?.map((a:any)=>a.user.name).join(', ')||'',deadline:t.currentDeadline,priority:priorityFromApi(t.priority),notes:t.description});
const taskPayload=(t:Partial<ShowTask>)=>({title:t.title,description:t.description??t.notes,category:t.category,phase:t.phase,department:t.department,startDate:t.startDate||null,plannedDeadline:t.plannedDeadline||t.deadline,currentDeadline:t.currentDeadline||t.deadline,priority:t.priority==='Khẩn cấp'?'URGENT':t.priority==='Quan trọng'?'IMPORTANT':'NORMAL',status:t.status,stuckReason:t.stuckReason});
export const userApi={list:()=>request<User[]>('/users')};
export const showApi={list:async()=>((await request<any[]>('/shows')).map(mapShow)),create:async(s:any)=>mapShow(await request('/shows',{method:'POST',body:JSON.stringify(s)})),update:async(id:string,s:any)=>mapShow(await request(`/shows/${id}`,{method:'PATCH',body:JSON.stringify(s)})),remove:(id:string)=>request<void>(`/shows/${id}`,{method:'DELETE'}),addMember:(showId:string,userId:string,role:string)=>request<ShowMember>(`/shows/${showId}/members`,{method:'POST',body:JSON.stringify({userId,role})}),updateMember:(id:string,role:string)=>request<ShowMember>(`/show-members/${id}`,{method:'PATCH',body:JSON.stringify({role})}),removeMember:(id:string)=>request<void>(`/show-members/${id}`,{method:'DELETE'})};
export const taskApi={forShow:async(id:string)=>(await request<any[]>(`/shows/${id}/tasks`)).map(mapTask),create:async(showId:string,t:Partial<ShowTask>)=>mapTask(await request(`/shows/${showId}/tasks`,{method:'POST',body:JSON.stringify(taskPayload(t))})),update:async(id:string,t:Partial<ShowTask>)=>mapTask(await request(`/tasks/${id}`,{method:'PATCH',body:JSON.stringify(taskPayload(t))})),remove:(id:string)=>request<void>(`/tasks/${id}`,{method:'DELETE'}),assign:(id:string,userId:string)=>request(`/tasks/${id}/assignees`,{method:'POST',body:JSON.stringify({userId})}),unassign:(id:string,userId:string)=>request<void>(`/tasks/${id}/assignees/${userId}`,{method:'DELETE'}),my:async()=>(await request<any[]>('/me/tasks')).map(mapTask),addDeliverable:(id:string,title:string,url:string)=>request<TaskDeliverable>(`/tasks/${id}/deliverables`,{method:'POST',body:JSON.stringify({title,url})}),removeDeliverable:(id:string)=>request<void>(`/deliverables/${id}`,{method:'DELETE'})};
