import React,{useMemo,useState} from 'react';
import {Plus,Trash2,UserPlus} from 'lucide-react';
import {useOps} from '../context/OpsContext';
import type {ShowInfo,ShowMemberRole,ShowTask} from '../types';
const roles:ShowMemberRole[]=['PM','PA1','PA2','PA3','SE','SSE','PE','SAE','PRODUCTION','SOCIAL','TALENT_ASSISTANT','OTHER'];
export const ShowOperationsPanel:React.FC<{show?:ShowInfo;tasks:ShowTask[];onAssign:(t:ShowTask)=>void}>=({show,tasks,onAssign})=>{
 const{users,currentUser,addShowMember,updateShowMember,removeShowMember}=useOps();const[tab,setTab]=useState<'summary'|'staff'>('summary');const[userId,setUserId]=useState('');const[role,setRole]=useState<ShowMemberRole>('SE');
 const stats=useMemo(()=>({done:tasks.filter(t=>t.status==='DONE').length,progress:tasks.filter(t=>t.status==='IN_PROGRESS').length,stuck:tasks.filter(t=>t.status==='STUCK').length,unassigned:tasks.filter(t=>!t.assignees?.length)}),[tasks]);if(!show)return null;
 return <section className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 space-y-4">
  <div className="flex gap-2"><button onClick={()=>setTab('summary')} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${tab==='summary'?'bg-amber-500 text-slate-950':'bg-slate-100 dark:bg-slate-800'}`}>Tổng quan</button><button onClick={()=>setTab('staff')} className={`px-3 py-1.5 rounded-lg text-xs font-bold ${tab==='staff'?'bg-amber-500 text-slate-950':'bg-slate-100 dark:bg-slate-800'}`}>Nhân sự Show ({show.members?.length||0})</button></div>
  {tab==='summary'?<><div className="grid grid-cols-2 md:grid-cols-6 gap-3">{[['Progress',`${tasks.length?Math.round(stats.done/tasks.length*100):0}%`],['Total',tasks.length],['Done',stats.done],['In progress',stats.progress],['Stuck',stats.stuck],['Unassigned',stats.unassigned.length]].map(([a,b])=><div key={a} className="rounded-xl bg-slate-50 dark:bg-slate-800 p-3"><div className="text-[10px] uppercase text-slate-500">{a}</div><div className="text-xl font-black">{b}</div></div>)}</div><div><h3 className="font-black text-rose-600 text-sm mb-2">TASK CHƯA CÓ NGƯỜI ĐẢM NHẬN</h3>{!stats.unassigned.length?<p className="text-sm text-slate-500">Tất cả công việc đã được phân công.</p>:<div className="space-y-2">{stats.unassigned.map(t=><div key={t.id} className="flex items-center justify-between border border-rose-200 dark:border-rose-900 rounded-xl p-3"><div><div className="font-bold text-sm">{t.title}</div><div className="text-xs text-slate-500">{new Date(t.currentDeadline||t.deadline).toLocaleDateString('vi-VN')} · {t.priority}</div></div>{currentUser?.companyRole==='MANAGER'&&<button onClick={()=>onAssign(t)} className="px-3 py-1.5 rounded-lg bg-rose-600 text-white text-xs font-bold">Phân công</button>}</div>)}</div>}</div></>:<><div className="grid md:grid-cols-5 gap-2"><select value={userId} onChange={e=>setUserId(e.target.value)} className="md:col-span-3 p-2 rounded-lg bg-slate-100 dark:bg-slate-800"><option value="">Chọn nhân sự</option>{users.filter(u=>!show.members?.some(m=>m.userId===u.id)).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select value={role} onChange={e=>setRole(e.target.value as ShowMemberRole)} className="p-2 rounded-lg bg-slate-100 dark:bg-slate-800">{roles.map(r=><option key={r}>{r}</option>)}</select><button disabled={!userId} onClick={()=>{void addShowMember(show.id,userId,role);setUserId('')}} className="bg-amber-500 disabled:opacity-40 rounded-lg font-bold text-xs flex items-center justify-center gap-1"><UserPlus size={14}/>Thêm</button></div><div className="space-y-2">{show.members?.map(m=>{const assigned=tasks.filter(t=>t.assignees?.some(a=>a.userId===m.userId));const done=assigned.filter(t=>t.status==='DONE').length;return <div key={m.id} className="grid grid-cols-6 items-center gap-2 border-b border-slate-100 dark:border-slate-800 py-2 text-sm"><div className="col-span-2 font-bold">{m.user.name}</div><select value={m.role} disabled={currentUser?.companyRole!=='MANAGER'} onChange={e=>void updateShowMember(m.id,e.target.value as ShowMemberRole)} className="bg-transparent"><option>{m.role}</option>{roles.filter(r=>r!==m.role).map(r=><option key={r}>{r}</option>)}</select><div>{assigned.length} Tasks</div><div>{done} Done · {assigned.length?Math.round(done/assigned.length*100):0}%</div>{currentUser?.companyRole==='MANAGER'&&<button onClick={()=>void removeShowMember(m.id)} className="justify-self-end text-rose-500"><Trash2 size={15}/></button>}</div>})}</div></>}
 </section>
}
